language: ruby
rvm:
  - 1.9.3
  - 2.1.0
  - 2.2.0
  - jruby-19mode
  - jruby-head
  - rbx-2

env: LANG="en_US.UTF-8" LC_ALL="en_US.UTF-8"

matrix:
  allow_failures:
    rvm:
    - ruby-head
    - rbx-2
